"""Brewfile formatting with Anthropic API integration.

This module handles formatting Brewfiles using the Anthropic API to add
descriptions, categorization, and documentation.
"""

import anthropic


class BrewfileFormatterError(Exception):
    """Exception raised for Brewfile formatting errors."""

    pass


def build_formatting_prompt(raw_content: str) -> str:
    """Build the prompt for Anthropic API to format a Brewfile.

    Args:
        raw_content: The raw Brewfile content from brew bundle dump.

    Returns:
        The formatted prompt string for the Anthropic API.
    """
    return f"""Format the following Brewfile with these requirements:

1. Add a header block at the top with:
   - "# Homebrew Brewfile"
   - "# Generated by den - https://github.com/wiscotrashpanda/den"
   - A brief description of the file's purpose
   - Usage instructions: "Use 'brew bundle' to install all packages, 'brew bundle cleanup' to remove unlisted packages."

2. Organize packages into logical categories with decorated section headers using this exact format:
   # ============================================
   # Category Name
   # ============================================

3. Add inline description comments at the END of each package line (not above), using this format:
   brew "package-name"                    # Brief description of what it does
   cask "app-name"                        # Brief description of what it does
   
   Align the comments for readability within each section.

4. Use these category groupings (adapt as needed based on packages present):
   - Custom Taps
   - Development Tools - Core
   - Development Tools - Languages & Runtimes
   - Infrastructure & DevOps
   - Container & Orchestration Tools
   - System Utilities
   - Shell & Terminal Enhancements
   - AI & Productivity CLI Tools
   - Security & Authentication
   - Web Browsers
   - Code Editors & IDEs
   - Terminal Emulators
   - AI & LLM Applications
   - Development & API Tools
   - Productivity & Organization
   - Communication
   - Media & Entertainment
   - Fonts
   - Visual Studio Code Extensions
   - Go Tools

5. Preserve ALL original package entries - do not remove or modify any packages

Return ONLY the formatted Brewfile content, no explanations or markdown code blocks.

Raw Brewfile:
{raw_content}"""


def format_brewfile(raw_content: str, api_key: str) -> str:
    """Send Brewfile to Anthropic for formatting with descriptions.

    Args:
        raw_content: The raw Brewfile content from brew bundle dump.
        api_key: Anthropic API key for authentication.

    Returns:
        The formatted Brewfile content with descriptions and categories.

    Raises:
        BrewfileFormatterError: If the API call fails.
    """
    prompt = build_formatting_prompt(raw_content)

    try:
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )
        # Extract text content from the response
        if message.content and len(message.content) > 0:
            return message.content[0].text
        raise BrewfileFormatterError("Empty response from Anthropic API")
    except anthropic.APIConnectionError as e:
        raise BrewfileFormatterError(f"Failed to connect to Anthropic API: {e}") from e
    except anthropic.RateLimitError as e:
        raise BrewfileFormatterError(f"Anthropic API rate limit exceeded: {e}") from e
    except anthropic.APIStatusError as e:
        raise BrewfileFormatterError(
            f"Anthropic API error: {e.status_code} - {e.message}"
        ) from e
