"""Unit tests for the Brewfile formatter module.

These tests verify Brewfile formatting with mocked Anthropic API calls.
"""

from unittest.mock import patch, MagicMock

import pytest
import anthropic

from den.brewfile_formatter import (
    build_formatting_prompt,
    format_brewfile,
    BrewfileFormatterError,
)


class TestBuildFormattingPrompt:
    """Tests for build_formatting_prompt function."""

    def test_prompt_includes_raw_content(self) -> None:
        """Test that the prompt includes the raw Brewfile content."""
        raw_content = 'brew "git"\nbrew "vim"'
        prompt = build_formatting_prompt(raw_content)

        assert raw_content in prompt

    def test_prompt_includes_header_instruction(self) -> None:
        """Test that the prompt instructs to add a header noting den generated the file."""
        raw_content = 'brew "git"'
        prompt = build_formatting_prompt(raw_content)

        assert "header" in prompt.lower()
        assert "den" in prompt
        assert "brew bundle" in prompt.lower()
        assert "brew bundle cleanup" in prompt.lower()

    def test_prompt_includes_inline_description_instruction(self) -> None:
        """Test that the prompt instructs to add inline descriptions at end of each line."""
        raw_content = 'brew "git"'
        prompt = build_formatting_prompt(raw_content)

        assert "description" in prompt.lower()
        assert "inline" in prompt.lower()
        assert "end of each" in prompt.lower()

    def test_prompt_includes_decorated_section_headers(self) -> None:
        """Test that the prompt instructs to use decorated section headers."""
        raw_content = 'brew "git"'
        prompt = build_formatting_prompt(raw_content)

        assert "============" in prompt
        assert "categor" in prompt.lower()  # matches categorize, categories, etc.

    def test_prompt_includes_preservation_instruction(self) -> None:
        """Test that the prompt instructs to preserve all original entries."""
        raw_content = 'brew "git"'
        prompt = build_formatting_prompt(raw_content)

        assert "preserve" in prompt.lower()


class TestFormatBrewfile:
    """Tests for format_brewfile function."""

    def test_successful_formatting(self) -> None:
        """Test successful Brewfile formatting returns formatted content."""
        mock_content_block = MagicMock()
        mock_content_block.text = '# Generated by den\nbrew "git"  # Version control'

        mock_message = MagicMock()
        mock_message.content = [mock_content_block]

        with patch("den.brewfile_formatter.anthropic.Anthropic") as mock_anthropic:
            mock_client = MagicMock()
            mock_client.messages.create.return_value = mock_message
            mock_anthropic.return_value = mock_client

            result = format_brewfile('brew "git"', "test_api_key")

            assert "Generated by den" in result
            mock_client.messages.create.assert_called_once()

    def test_api_connection_error(self) -> None:
        """Test that connection errors raise BrewfileFormatterError."""
        with patch("den.brewfile_formatter.anthropic.Anthropic") as mock_anthropic:
            mock_client = MagicMock()
            mock_client.messages.create.side_effect = anthropic.APIConnectionError(
                request=MagicMock()
            )
            mock_anthropic.return_value = mock_client

            with pytest.raises(BrewfileFormatterError) as exc_info:
                format_brewfile('brew "git"', "test_api_key")

            assert "Failed to connect" in str(exc_info.value)

    def test_rate_limit_error(self) -> None:
        """Test that rate limit errors raise BrewfileFormatterError."""
        mock_response = MagicMock()
        mock_response.status_code = 429

        with patch("den.brewfile_formatter.anthropic.Anthropic") as mock_anthropic:
            mock_client = MagicMock()
            mock_client.messages.create.side_effect = anthropic.RateLimitError(
                message="Rate limit exceeded",
                response=mock_response,
                body=None,
            )
            mock_anthropic.return_value = mock_client

            with pytest.raises(BrewfileFormatterError) as exc_info:
                format_brewfile('brew "git"', "test_api_key")

            assert "rate limit" in str(exc_info.value).lower()

    def test_api_status_error(self) -> None:
        """Test that API status errors raise BrewfileFormatterError."""
        mock_response = MagicMock()
        mock_response.status_code = 401

        with patch("den.brewfile_formatter.anthropic.Anthropic") as mock_anthropic:
            mock_client = MagicMock()
            mock_client.messages.create.side_effect = anthropic.APIStatusError(
                message="Invalid API key",
                response=mock_response,
                body=None,
            )
            mock_anthropic.return_value = mock_client

            with pytest.raises(BrewfileFormatterError) as exc_info:
                format_brewfile('brew "git"', "bad_api_key")

            assert "Anthropic API error" in str(exc_info.value)

    def test_empty_response_error(self) -> None:
        """Test that empty API response raises BrewfileFormatterError."""
        mock_message = MagicMock()
        mock_message.content = []

        with patch("den.brewfile_formatter.anthropic.Anthropic") as mock_anthropic:
            mock_client = MagicMock()
            mock_client.messages.create.return_value = mock_message
            mock_anthropic.return_value = mock_client

            with pytest.raises(BrewfileFormatterError) as exc_info:
                format_brewfile('brew "git"', "test_api_key")

            assert "Empty response" in str(exc_info.value)
